name = "Chic"
grammar = "chic"
path_suffixes = ["chic"]
line_comments = ["// "]
tab_size = 4
hard_tabs = false
word_characters = ["_", "@", "#"]

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
]
